controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  legged_controller:
    type: legged/LeggedController
  legged_controller_projected_wbc:
    type: legged/LeggedControllerProjectedWBC
  legged_cheater_controller:
    type: legged/LeggedCheaterController
  legged_cheater_controller:
    type: legged/LeggedCheaterControllerProjectedWBC
